# Employee Data Analysis and Preprocessing using Python

#Project Objective

The objective of this project is to claen and preprocess raw employee salary data obtained from 
an Excel file.Using Python and Pandas,the data is cleaned and transformed into analysis-ready 
dataset for further insights and reporting.

In [2]:
import pandas as pd #importing the file 
df=pd.read_excel(r"C:\Users\DHANASHREE\Downloads\employee_data_cleaned.xlsx")

In [3]:
df.info()          #checking the structure of the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Employee_ID  15 non-null     int64
 1   Name         15 non-null     object
 2   Age          13 non-null     float64
 3   Gender       15 non-null     object
 4   Department   14 non-null     object
 5   Experience   15 non-null     object
 6   Salary       14 non-null     float64
 7   Join_Date    15 non-null     datetime64[ns]
 8   City         15 non-null     object
dtypes: datetime64[ns](1), float64(2), int64(1), object(5)
memory usage: 1.2+ KB

In [4]:
df.head(6)          #preview of data

,Employee_ID,Name,Age,Gender,Department,Experience,Salary,Join_Date,City
0,101,Amit Sharma,29.0,Male,Finance,3 years,45000.0,2021-05-12,Mumbai
1,102,Neha Patil,NaN,Female,HR,2 yrs,38000.0,2021-06-15,Pune
2,103,Rahul Verma,45.0,M,IT,20 years,120000.0,2010-03-15,Delhi
3,104,Pooja Singh,32.0,Female,Marketing,5 years,NaN,2019-11-20,Bangalore
4,105,Suresh Kumar,-5.0,Male,Finance,1 year,25000.0,2022-01-10,Chennai
5,106,Anjali Mehta,28.0,female,IT,2 years,40000.0,2021-07-10,mumbai

In [5]:
df.isnull().sum()        #identified missing values

Employee_ID    0
Name           0
Age            2
Gender         0
Department     1
Experience     0
Salary         1
Join_Date      0
City           0
dtype: int64

# Handling Missing Data

In [6]:
#Handling missing values in [AGE] column:
df['Age']=df['Age'].fillna(df['Age'].median())    #fills average age in missing places
df=df[df['Age']>0]                              #(>0) cleans unrealistic values
df['Age'].describe()                             #shows the column statistics

count    14.000000
mean     34.357143
std       8.767134
min      26.000000
25%      29.000000
50%      31.000000
75%      37.750000
max      58.000000
Name: Age, dtype: float64

After cleaning the AGE column,descriptive statistics were generated to validate results.
The minimum age was 26 and the maximum age was 58,indicating the invalid values were succesfully removed .
The median age was 31 confirming appropriate handling of the missing values using the median.

In [7]:
#Handling missing values in [Salary] column:
df['Salary']=df['Salary'].fillna(df['Salary'].median())
df=df[df['Salary']>0]
df['Salary'].describe()

count        13.000000
mean      65000.000000
std       61726.547503
min       18000.000000
25%       38000.000000
50%       40000.000000
75%       55000.000000
max      250000.000000
Name: Salary, dtype: float64

In [8]:
df.head()

,Employee_ID,Name,Age,Gender,Department,Experience,Salary,Join_Date,City
0,101,Amit Sharma,29.0,Male,Finance,3 years,45000.0,2021-05-12,Mumbai
1,102,Neha Patil,31.0,Female,HR,2 yrs,38000.0,2021-06-15,Pune
2,103,Rahul Verma,45.0,M,IT,20 years,120000.0,2010-03-15,Delhi
3,104,Pooja Singh,32.0,Female,Marketing,5 years,40000.0,2019-11-20,Bangalore
5,106,Anjali Mehta,28.0,female,IT,2 years,40000.0,2021-07-10,mumbai

After cleaning the Salary column,descriptive statsitics were generated to validate the results.Negative salary values were removed, and missing salaries were filled using the median.The minimum salary was ₹18,000 and the maximum was ₹2,50,000 ;indicating distribution.

In [9]:
#Handling values in [Gender] column:
#Standardizing gender into only two columns [Male] [Female]:
df['Gender'].unique()     #this finds unique values from the column

array(['Male', 'Female', 'M', 'female'], dtype=object)

In [10]:
#Converting all values to lowercase
df['Gender']=df['Gender'].str.lower().str.strip()

In [11]:
df['Gender']=df['Gender'].replace({
    'm':'Male',
    'male':'Male',
    'f':'Female',
    'female':'Female'
})
df['Gender'].value_counts()

Gender
Female    7
Male      6
Name: count, dtype: int64

In [12]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

The Gender column was standardizied by converting all the entries to lowercase and removing extra spaces .Inconsistent values like 'm' and 'f' were mapped to 'Male' and 'Female' to ensure the data uniformity .The final check confirms only two unique categories.

In [13]:
#Cleaning Experience Column:
#Converting Experience into a numerice column (years):
#Experience(int)
df['Experience'].unique()

array(['3 years', '2 yrs', '20 years', '5 years', '2 years', '15 years',
       '1 year', '35 years', '4 years', 'three years', '8 years'],
      dtype=object)

In [14]:
#Converting into lowercase
df['Experience']=df['Experience'].str.lower().str.strip()

In [16]:
word_to_num={
    'one':'1',
    'two':'2',
    'three':'3',
    'four':'4',
    'five':'5'
}
df['Experience']=df['Experience'].replace(word_to_num,regex=True)

In [19]:
#Extracting numeric Values & Converting to Integer
df['Experience']= df['Experience'].str.extract(r'(\d+)').astype(int)
df[['Experience']].head()

   Experience
0           3
1           2
2          20
3           5
5           2

In [22]:
#resetting index values 
df = df.reset_index(drop=True)          #(drop) don’t keep old index

In [23]:
df[['Experience']].head()

   Experience
0           3
1           2
2          20
3           5
4           2

The Experience column contained inconsistent data vlauessuch as "3 years","2 yrs" and "three years".All values were converted to lowercase,word based numbers were mapped to digits . The clumn was then converted to an intefer format representing years of experience.

In [24]:
#Cleaning City Comun
df['City'].unique()

array(['Mumbai', 'Pune', 'Delhi', 'Bangalore', 'mumbai', 'Ahmednagar',
       'Bengaluru', 'Kochi', 'Chennai'], dtype=object)

In [25]:
#Removed leading & trailing spaces
df['City']=df['City'].str.strip()

In [26]:
#Standardizing Capitalization
df['City']=df['City'].str.title()

In [27]:
#Fixing differnt spellings
#Bangalore & Bengaluru should be one city
df['City']=df['City'].replace({'Bengaluru':'Bangalore'})

In [28]:
#Verifying cleaned cities
df['City'].value_counts()

City
Pune          3
Delhi         3
Mumbai        2
Bangalore     2
Ahmednagar    1
Kochi         1
Chennai       1
Name: count, dtype: int64

The City column contained inconsistent text values due to different capitalizations, extra spaces, and alternate spellings.
To clean the data, leading and trailing spaces were removed, text was standardized to title case, and alternate city names were mapped to a single standard value.

In [29]:
#Cleaning the Join_Date Column:
df['Join_Date'].dtype          #checking type first

dtype('<M8[ns]')

In [30]:
#Checking missing value:
df['Join_Date'].isna().sum()   #isna() is used to check for actual missing values

0

In [31]:
#Finding the invalid rows
bad_dates = df[df['Join_Date'].isna()]
bad_dates

Empty DataFrame
Columns: [Employee_ID, Name, Age, Gender, Department, Experience, Salary, Join_Date, City]
Index: []

In [33]:
#Taking only the year from the date and storing it in a new column
df['Join_Year'] = df['Join_Date'].dt.year

This indicates there was no need of clleaning date column as its was cleaned first handedly in excel.

In [35]:
#Cleaning Department Column 
df['Department'].unique()

array(['Finance', 'HR', 'IT', 'Marketing', 'Sales', nan], dtype=object)

In [36]:
#filling the missing values
df['Department'] = df['Department'].fillna(df['Department'].mode()[0])

In [37]:
df.isna().sum()

Employee_ID    0
Name           0
Age            0
Gender         0
Department     0
Experience     0
Salary         0
Join_Date      0
City           0
Join_Year      0
dtype: int64

This (0) infront of every column name indicates that all the columns have beaan cleaned and there are no missing values in the columns and ; hence the data is now ready for the further  exploratory analysis process.

# MOVING FORWARD TO EXPLORATORY DATA ANALYSIS

In [38]:
#GETTING BASIC STATISTICS TO GET INSIGHTS FROM DATA

Analysis Question 1- Which department pays the highest average salary?

In [39]:
df.groupby('Department')['Salary'].mean().sort_values(ascending= False)
#ADDING (.sort values shoes the highest paying first)

Department
IT           136666.666667
Finance       67500.000000
HR            39250.000000
Sales         36500.000000
Marketing     35000.000000
Name: Salary, dtype: float64

In [ ]:
IT Department pays the highest salary compared to any other.

Analysis Question 2- Which city has the highest average salary?

In [41]:
df.groupby('City')['Salary'].mean().sort_values(ascending= False)

City
Delhi         141666.666667
Bangalore      65000.000000
Mumbai         42500.000000
Kochi          42000.000000
Chennai        39000.000000
Pune           35333.333333
Ahmednagar     18000.000000
Name: Salary, dtype: float64

Employees in Delhi city have the highest average salary.

Analysis Question 3-Does Experience Affect Salary?

In [43]:
df.groupby('Experience')['Salary'].mean().sort_values(ascending= False)

Experience
15    250000.000000
20    120000.000000
35     90000.000000
8      55000.000000
3      42000.000000
4      42000.000000
5      40000.000000
2      38666.666667
1      24000.000000
Name: Salary, dtype: float64

Analysis Question 4 - Which year had the most employee hiring?

In [45]:
df['Join_Year'] = df['Join_Date'].dt.year
df['Join_Year'].value_counts()

Join_Year
2021    5
2010    1
2019    1
2015    1
2023    1
2005    1
2020    1
2022    1
2018    1
Name: count, dtype: int64

Analysis Question 5 -Which department has highest numbers of employees?

In [52]:
df['Department'].value_counts()

Department
HR           4
IT           3
Finance      2
Marketing    2
Sales        2
Name: count, dtype: int64

“The HR department has the highest number of employees, indicating a higher demand for Human Resource roles within the organization.

In [ ]:
Analysis Question 6-Which city has the most employees?

In [53]:
df['City'].value_counts()

City
Pune          3
Delhi         3
Mumbai        2
Bangalore     2
Ahmednagar    1
Kochi         1
Chennai       1
Name: count, dtype: int64

"PUNE" & "DELHI" has the highest employee count, making it the primary workforce hub.

# Final Report: Employee Data Analysis Project

This project focused on analyzing employee data to extract meaningful insights related to salary distribution, hiring trends, and workforce composition. Through this analysis, several key business questions were explored and answered using Python and pandas.

Throughout the project, essential data cleaning techniques were applied, such as handling missing values using median imputation and removing invalid entries. Key pandas operations including filtering, grouping, aggregation, and sorting were used effectively to perform the analysis.

#Key Skills Demonstrated:

1] Data Cleaning and Preprocessing
2] Handling Missing Values
3] Data Filtering and Transformation
4] GroupBy Operations and Aggregation
5] Basic Statistical Analysis
6] Insight Generation for Business Problems

This project marks a solid foundation in the journey toward becoming a data analyst and showcases the ability to translate data into meaningful insights.